Database setup initial
Voytima/User-management pull request #2
Opened 2023-10-25 13:00 UTC by Voytima

Database setup initial

2023-10-25 15:14 UTC, Usmik requested changes
and rethink which fields should be indexed

2023-10-25 15:14 UTC, Usmik commented on src/database.py
> +        await session.close()
use async context manager for this

2023-10-25 15:14 UTC, Usmik commented on src/users/models.py
> +    name: Mapped[str] = mapped_column(String(64), unique=True, nullable=True)
could name of group be nullable?

2023-10-25 15:14 UTC, Usmik commented on src/users/models.py
> +    surname: Mapped[str] = mapped_column(String(80), nullable=False)
actually it's fine to set it's explicitly like nullable=False, but it will be false by default

2023-10-25 15:14 UTC, Usmik commented on src/users/models.py
> +    surname: Mapped[str] = mapped_column(String(80), nullable=False)
and check how for example for Mapped[str] show it's nullable (not only by Optional, but it's also a good one)

2023-10-25 15:14 UTC, Usmik commented on src/users/models.py
> +    role: Mapped[Role] = mapped_column(nullable=False, index=True)
set default role

2023-10-25 15:14 UTC, Usmik commented on src/users/models.py
> +    )
why additional (),  and use onupdate for modified_at

2023-10-26 08:17 UTC, Usmik requested changes

2023-10-26 08:17 UTC, Usmik commented on src/database.py
> +        retutn db.querry('SQL STATEMENT...')"""
оу, неа:) 
я имел в виду 
async with async_session() as session:
     yield session

2023-10-26 08:17 UTC, Usmik commented on src/settings.py
> +    pguser: str
why you rename it?)

2023-10-26 08:17 UTC, Usmik commented on src/users/models.py
> +    modified_at: Mapped[datetime] = mapped_column(onupdate=func.now())
and add also default value for modified at

2023-10-26 08:17 UTC, Usmik commented on src/users/models.py
> +    phone_number: Mapped[str] = mapped_column(nullable=True)
make it to be in one style: 
I mean you have 
1. mapped_column(nullable=True)
2. image: Mapped[Optional[str]]
use the second one

2023-10-26 09:23 UTC, Voytima commented on src/settings.py
> +    pguser: str
My docker-compose pgsql container swore at me because of this postgres_user and everything was ok when I renamed it to pguser. I renamed it back to postgres_user because locally everything works. If error for docker-compose occurs again, I rename it back to pguser then.

2023-10-26 14:21 UTC, Usmik approved these changes

2023-10-26 14:21 UTC, Usmik commented on src/database.py
> +@asynccontextmanager
remove decorator @asynccontextmanager

2023-10-27 09:28 UTC, merged