Some endpoints
Voytima/User-management pull request #5
Opened 2023-11-09 19:45 UTC by Voytima

Commented endpoint with query parameters as well as functions that are belong to it because it has not been done completely yet

2023-11-16 06:58 UTC, Usmik requested changes
1. **Remove**  logic from repositories. It should be in services
2. As an approach you can make services also a class, and in router you will have depends for Service, in init of Service -> Depends for Repo -> in Repo init Depends(get_session)

2023-11-16 06:58 UTC, Usmik commented on localstack/cache/machine.json
localstack/cache :(((

2023-11-16 06:58 UTC, Usmik commented on Pipfile
> +wheel = "*"
wheel = "*" specify version

2023-11-16 06:58 UTC, Usmik commented on test_aws.png
??

2023-11-16 06:58 UTC, Usmik commented on src/aws/service.py
> +        endpoint_url="http://localstack:4566",
endpoint url - also secret info

2023-11-16 06:58 UTC, Usmik commented on src/users/dependencies.py
> +    token: Annotated[str, Header()], session: AsyncSession = Depends(get_session)
from docs https://fastapi.tiangolo.com/tutorial/header-params/#__tabbed_1_4
`async def read_items(user_agent: str | None = Header(default=None)):
`

2023-11-16 06:58 UTC, Usmik commented on src/users/user_repository.py
> +class CRUDGroups(CRUDBase[User]):
fix naming

2023-11-16 06:58 UTC, Usmik commented on src/users/router.py
logic should be in services, not in routers

2023-11-16 06:58 UTC, Usmik commented on src/groups/utils.py
why need for this utils?

2023-11-16 06:59 UTC, Usmik commented on src/abstract_repository.py
it's actually not an abstract class, check the file naming

2023-11-16 08:20 UTC, Voytima commented on alembic/env.py
> +config.set_section_option(section, "DB_HOST", os.environ.get("POSTGRES_DOCKER_HOST"))
Because earlier I tested my app also on local machine and docker, but nowadays everything is using docker. I forgot to remove unused rows, my fault, sorry

2023-11-17 13:36 UTC, Usmik requested changes

2023-11-17 13:36 UTC, Usmik commented on entrypoint.sh
> +alembic upgrade head
no need to run this every time, you will have empty migrations

2023-11-17 13:36 UTC, Usmik commented on localstack/cache/machine.json
localstack still here:)

2023-11-17 13:36 UTC, Usmik commented on test_aws.png
still here))

2023-11-17 13:36 UTC, Usmik commented on src/users/user_repository.py
> +user_repository = UserRepository(get_session())
```suggestion

```

2023-11-17 13:36 UTC, Usmik commented on src/users/service.py
> +    def __init__(self, user_repository: UserRepository):
add depends for UserRepo

2023-11-17 13:36 UTC, Usmik commented on src/users/router.py
> +from src.users.utils import check_user_permissions  # filter_users,
remove comments

2023-11-17 13:36 UTC, Usmik commented on src/users/router.py
> +from ..models import User
don't use relative imports

2023-11-17 13:36 UTC, Usmik commented on src/users/service.py
> +# from src.users.user_repository import user_repository
comments

2023-11-17 13:36 UTC, Usmik commented on src/users/service.py
> +    def __init__(self, user_repository: UserRepository):
```suggestion
    def __init__(self, user_repository: UserRepository = Depends()):
```

2023-11-17 13:36 UTC, Usmik commented on src/users/dependencies.py
> +from ..models import Role
relative imports

2023-11-17 13:36 UTC, Usmik commented on src/groups/group_repository.py
> +    def __init__(self, db=get_session()):
Depends()

2023-11-21 07:00 UTC, Usmik approved these changes

2023-11-21 07:00 UTC, Usmik commented on docker-compose.yml
> +    image: redis:latest
fix redis:latest

2023-11-21 07:08 UTC, merged